import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import Footer from '@/components/Footer'
import AuthProvider from '@/providers/AuthProvider'
import QueryProvider from '@/providers/QueryProvider'
import { ToastContainer } from 'react-toastify';
  import 'react-toastify/dist/ReactToastify.css';

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mug Style',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={rubik.className}>
        <AuthProvider>
          <QueryProvider>
            <Navbar/>
            {children}
            <Footer/>
            <ToastContainer position='bottom-right' theme='dark' autoClose={3000} />
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
