import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import Footer from '@/components/Footer'
import AuthProvider from '@/providers/AuthProvider'
import QueryProvider from '@/providers/QueryProvider'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mug Style',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={rubik.className}>
        <AuthProvider>
          <QueryProvider>
            <Navbar/>
            {children}
            <Footer/>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
